/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.view;

import java.util.Scanner;
import oop.shape.Circle;
import oop.shape.Rectangle;
import oop.shape.RightTriangle;
import oop.shape.Shape;
import oop.shape.Triangle;

/**
 *
 * @author Administrator
 */
public class OOP extends javax.swing.JDialog {

    private int index;
    private static final String[] MSG = {
        "请选择图形",
        "请输入半径",
        "请输入三条边",
        "请输入两条直角边",
        "请输入两条边",};

    /**
     * Creates new form OOP
     */
    public OOP(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jComboBoxShape = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldPara = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1Result = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("图形选择");

        jComboBoxShape.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "请选择一个图形", "圆", "三角形", "直角三角形", "矩形" }));
        jComboBoxShape.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxShapeItemStateChanged(evt);
            }
        });
        jComboBoxShape.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxShapeActionPerformed(evt);
            }
        });

        jLabel2.setText("参数输入（注：参数之间以空格隔开）");

        jTextFieldPara.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldParaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldParaFocusLost(evt);
            }
        });
        jTextFieldPara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldParaActionPerformed(evt);
            }
        });

        jTextArea1Result.setEditable(false);
        jTextArea1Result.setColumns(20);
        jTextArea1Result.setRows(5);
        jScrollPane1.setViewportView(jTextArea1Result);

        jButton1.setText("计算");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("计算结果");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBoxShape, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextFieldPara)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(0, 207, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxShape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldPara, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxShapeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxShapeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxShapeActionPerformed

    private void jTextFieldParaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldParaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldParaActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (index <= 0) {
            return;
        }
        try {
            String data = jTextFieldPara.getText();
            Scanner input = new Scanner(data);
            String[] para = data.split(" ");
            Shape shape;
            double[] edge = new double[para.length];
            for (int i = 0; i < edge.length; i++) {
                edge[i] = Double.parseDouble(para[i]);
            }
            switch (index) {
                case 0:
                    shape = null;
                    break;
                case 1:
                    shape = new Circle(edge[0]);
                    break;
                case 2:
                    shape = new Triangle(edge[0], edge[1], edge[2]);
                    break;
                case 3:
                    shape = new RightTriangle(edge[0], edge[1]);
                    break;
                case 4:
                    shape = new Rectangle(edge[0], edge[1]);
                    break;
                default:
                    shape = null;
                    break;
            }
            double d1 = shape.calculateArea();
            double d2 = shape.calculatePerimeter();
            String rs = "";
            rs += shape.toString() + '\n';
            rs += "周长 = " + d2 + '\n';
            rs += "面积 = " + d1 + '\n';
            jTextArea1Result.setText(rs);
        } catch (Exception e) {
            jTextArea1Result.setText("选择图形/参数输入错误");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBoxShapeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxShapeItemStateChanged
        jButton1.setEnabled(index > 0);
        index = jComboBoxShape.getSelectedIndex();
        jTextFieldPara.setText(MSG[index]);
        System.out.println(index);
    }//GEN-LAST:event_jComboBoxShapeItemStateChanged

    private void jTextFieldParaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldParaFocusGained
        jTextFieldPara.setText("");
        jTextArea1Result.setText("");
    }//GEN-LAST:event_jTextFieldParaFocusGained

    private void jTextFieldParaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldParaFocusLost

    }//GEN-LAST:event_jTextFieldParaFocusLost

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OOP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OOP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OOP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OOP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                OOP dialog = new OOP(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxShape;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1Result;
    private javax.swing.JTextField jTextFieldPara;
    // End of variables declaration//GEN-END:variables
}
